In [1]:
import numpy as np

In [2]:
images = [(" ", np.array([(12, 84, 140, 212),(24, 84, 152, 212),(36, 84, 164, 212),(12, 96, 140, 224),
(24, 96, 152, 224),(24, 108, 152, 236)]))]

In [3]:
images

[(' ', array([[ 12,  84, 140, 212],
         [ 24,  84, 152, 212],
         [ 36,  84, 164, 212],
         [ 12,  96, 140, 224],
         [ 24,  96, 152, 224],
         [ 24, 108, 152, 236]]))]

In [4]:
image = images[0][1]

In [5]:
image

array([[ 12,  84, 140, 212],
       [ 24,  84, 152, 212],
       [ 36,  84, 164, 212],
       [ 12,  96, 140, 224],
       [ 24,  96, 152, 224],
       [ 24, 108, 152, 236]])

In [6]:
boxes =  image

In [7]:
boxes

array([[ 12,  84, 140, 212],
       [ 24,  84, 152, 212],
       [ 36,  84, 164, 212],
       [ 12,  96, 140, 224],
       [ 24,  96, 152, 224],
       [ 24, 108, 152, 236]])

In [8]:
pick = []

In [9]:
x1 = boxes[: ,0]
x1

array([12, 24, 36, 12, 24, 24])

In [10]:
y1 = boxes[:, 1]
y1

array([ 84,  84,  84,  96,  96, 108])

In [11]:
x2 = boxes[:, 2]
y2 = boxes[:, 3]

print(x2 , y2 )

[140 152 164 140 152 152] [212 212 212 224 224 236]


In [12]:
area = (x2 - x1  + 1 )*( y2 - y1 +1 )
area

array([16641, 16641, 16641, 16641, 16641, 16641])

In [13]:
idxs = np.argsort(y2)
idxs

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [14]:
while len(idxs) > 0:
    last = len(idxs) - 1
    i = idxs[last]
    pick.append(i)
    suppress = [last]
    
    for pos in range(0,last):
        j = idxs[pos]
        xx1 = max( x1[i] , x1[j])
        yy1 = max( y1[i] , y1[j])
        
        xx2 = min( x2[i] , x2[j])
        yy2 = min( y2[i] , y2[j])
        
        w = max( 0 , xx2 -  xx1 +1 )
        h = max( 0 , yy2 - yy1 +1  )
        
        overlap = float(w*h)/area[j]
        
        if overlap > 0.3:
            suppress.append(pos)
            print(overlap)
            print(idxs)
            
        # delete all indexes from the index list that are in the suppression list
    
    idxs = np.delete(idxs , suppress)
    
    
    
    
    
    
    
    
        
    
    

0.738236884802596
[0 1 2 3 4 5]
0.813953488372093
[0 1 2 3 4 5]
0.738236884802596
[0 1 2 3 4 5]
0.8226068144943213
[0 1 2 3 4 5]
0.9069767441860465
[0 1 2 3 4 5]


In [17]:
pick

[5]

In [18]:
boxes[pick]

array([[ 24, 108, 152, 236]])